apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/checkout@v1
        name: checkout-source-code
      - uses: cloudbees-io/gosec-sast-scan-code@v1
        name: Run gosec (SO)
        kind: scan
